### ISSUE TITLE
'Citation Policy' link in Publications tab missing

### ISSUE THREAD

**Issue by saraelshawa** [langcog/metalab#35]

**Comment by saraelshawa** [comment]
from old website: https://langcog.github.io/metalab2/publications.html

**Comment by christinabergmann** [comment]
(Note also the difference in subsections)

**Comment by erikriverson** [comment]
This is fixed now.

**Comment by christinabergmann** [comment]
The citation policy leads to a blank document. 

I also want to flag the subsections as something we might want to reconsider.

**Comment by saraelshawa** [comment]
@christinabergmann "Citation Policy" link in Publications tab leads to "Citation Policy" in Documentation under "Using MetaLab Data". Am I missing something?

**Comment by christinabergmann** [comment]
You're right, it looks good now.
