### ISSUE TITLE
Publications - papers describing the meta-analyses?

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab#40]
Would it make sense to have a section under Publications that collects all reports on the meta-analyses currently on metalab?

(Ideally below the papers we ask people to cite, see issue #35 and below the papers using MetaLab, i.e. right now the two proceedings papers).

**Comment by lottiegasp** [comment]
Could this feed directly from the item "link" in metadata/datasets.yaml? But we would want a way for only publications/manuscripts to show up (as opposed to databases with no manuscript?)

**Comment by christinabergmann** [comment]
Or from full_citation plus link? We could skip those where full_citation is empty.

**Comment by lottiegasp** [comment]
Good idea.
Just checking - Would we want to include registrations (Sho and I had discussed including instructions for how to pre-register on OSF, so hopefully there will be more of these) and in submission/progress preprints, or only published articles? As all of these would have full_citation

**Comment by christinabergmann** [comment]
Anything citable would be ok for me. Google Scholar merges preprint/publication citations, for example.

**Comment by lottiegasp** [comment]
@erikriverson could you see if there's a way to feed directly from the link and full_citation fields of datasets.yaml to the Publications page of the website. Or if not, let me know and I will add them manually

**Comment by lottiegasp** [comment]
@saraelshawa I think it would be good if [Publications](http://metalab.stanford.edu/publications/) is structured as below. The list of "MetaLab meta-analyses" should contain those where the fields _full_citation_ or _paper_link_ in datasets.yaml are filled, and are excluded from the list if either is empty.

**Publications**

**Citation Policy**

MetaLab encourages researchers to use data available on its website. For example, you can cite meta-analytic results, or download datasets and and conduct custom analyses. Before using MetaLab data in your publication, we ask that you please read our citation policy.

**MetaLab meta-analyses**
_full_citation_ [Paper](link to _paper_link_)
e.g.
Tsuji, S. & Cristia, A. (2014). Perceptual attunement in vowels: A meta-analysis. Developmental Psychobiology, 56(2), 179-191. [[Paper](https://pure.mpg.de/rest/items/item_1836135/component/file_1945376/content)]
etc.

**Publications that used existing MetaLab data**
Bergmann, C. Tsuji, S., & Cristia, A. (2017). Top-down versus bottom-up theories of phonological acquisition: A big data approach. In: Proceedings of Interspeech 2017, pp. 2013–2016. DOI: 10.21437/Interspeech.2017-1443 [Paper]
etc.

**Comment by lottiegasp** [comment]
Thanks @saraelshawa ! Just one request, could you have them come up in alphabetical order by first author? Thanks!

**Comment by saraelshawa** [comment]
No worries @lottiegasp :) Done!
