### ISSUE TITLE
Publications - to add to the section on papers using MetaLab

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab#41]
The following papers have used MetaLab and cited us appropriately, so it would be great to add them:

https://onlinelibrary.wiley.com/doi/abs/10.1002/jrsm.1464
Mathur, M. B., & VanderWeele, T. J. (2020). Estimating Publication Bias in Meta‐Analyses of Peer‐Reviewed Studies: A Meta‐Meta‐Analysis Across Disciplines and Journal Tiers. Research Synthesis Methods.

https://rss.onlinelibrary.wiley.com/doi/pdf/10.1111/rssc.12440
Mathur, M. B., & VanderWeele, T. J. (2020). Sensitivity analysis for publication bias in meta‐analyses. Journal of the Royal Statistical Society. Series C, Applied Statistics, 69(5), 1091.

https://econtent.hogrefe.com/doi/abs/10.1027/2151-2604/a000393?journalCode=zfp
Tsuji, S., Cristia, A., Frank, M. C., & Bergmann, C. (2020). Addressing Publication Bias in Meta-Analysis. Zeitschrift für Psychologie.

Please add any I am missing

**Comment by lottiegasp** [comment]
Done
