### ISSUE TITLE
No visualizations for some datasets

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab#52]
For me, visualizations sometimes show up, the N conditions and effect sizes appear, as does the funnel plot, but not the forest or bubble (effect by age) plot. 
I've found this to be the case for word segmentation and familiar word recognition, but there might be other datasets.

**Comment by erikriverson** [comment]
Thank you for the report. This is tracked down to datasets that have non-ASCII characters in the short_cite field. It relates to the way we were persisting data for the Shiny apps. Working on the fix, will be done shortly, and will update here!

**Comment by erikriverson** [comment]
Latest commit should fix this
