### ISSUE TITLE
Adding team members on MetaLab

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#57]
Hi @erikriverson can you help me add a team member on MetaLab? I added Fleur under _content>people_ in what I thought was the same structure as the other members, but she isn't showing up on the website

Also, I think the old way to do it (add team members to _metadata>people.yaml_) is now redundant, as I see that you, myself and Sara aren't in that file... can this be deleted now to avoid confusion?

**Comment by erikriverson** [comment]
Hey Lottie! I think you did it right, the index file for Fleur is just missing the extension. If you rename it to index.md it should work. 

For the second question, we may try to use people.yaml in the future to automatically generate the files under content/people, so let's leave it for now. Thank you!

**Comment by lottiegasp** [comment]
Thanks @erikriverson !
