### ISSUE TITLE
Failure to build and deploy

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#69]
I made changes to the Google Sheet tabular data of language-discrimination (to fix direction of effect sizes as per https://github.com/langcog/metalab/issues/39) and it is failing to build and deploy (see last three [Actions](https://github.com/langcog/metalab/actions)). 

@erikriverson Let me know if there is a process I should follow whenever editing the Google Sheet tabular data to avoid this

I assume this is why the Applications on the website are not working at the moment?

**Comment by erikriverson** [comment]
The disk on the machine the Shiny server runs on had filled up. I deleted some logs and restarted the server and the apps are back up. Closing this one for now.
