### ISSUE TITLE
Estimating corr/dependencies in the data

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#80]
Following on from https://github.com/langcog/metalab/issues/68 to find a long-term optimal method for estimating corr/dependencies in datasets.

MetaLab script's current method for imputing missing corr values is to randomly select from other existing values in the dataset (perhaps limited to the same method/similar age). In langdiscrim we imputed from a normal distribution using the median and variance of existing corr values and then adjusting the range to [-1,1]. Rabagliati et al. (2018) imputed it as the mean weighted by sample size.

We will work on a short report (/paper in the long run) where we review the literature for other methods, then compare the methods for the site, then decide on the best option

**Comment by lottiegasp** [comment]
One option to consider is Robust Variance Estimation which uses the package clubSandwich alongside rma.mv in metafor to develop a working model based on an estimate of variance. Need to look further into this to see if it could be integrated with MetaLab's approach of estimating corr before calculating effect sizes

https://osf.io/vyfcj/
https://youtu.be/Q9Nce5pxebY?t=50

**Comment by christinabergmann** [comment]
Yes, we need to move to robumeta with clubsandwich in the long run. It was mentioned here, but got lost: https://github.com/langcog/metalab2/issues/135#issuecomment-497918729

**Comment by lottiegasp** [comment]
Thanks @christinabergmann! Okay, reading through these I see that I misunderstood 'dependencies' as it relates to Robust Variance Estimation to relate to the corr column when it actually relates to random effects structure! I will just transfer the Issue you tagged from metalab2 to the metalab repo so it's still on our radar
