### ISSUE TITLE
Data extraction tools 

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab#9]
We could expand suggestions for data extraction and give recommendations on how to transparently document data extraction.

One example is the tabulizer R package that extracts tables from pdfs
https://www.rdocumentation.org/packages/tabulizer/versions/0.2.2

**Comment by lottiegasp** [comment]
In the tutorial paper we decided to reference [WebPlotDigitizer](https://apps.automeris.io/wpd/) and the in-development R package digitizeR
